plugins:
  - "prettier-plugin-solidity"
printWidth: 120
trailingComma: "all"
endOfLine: "lf"
semi: true
singleQuote: false
quoteProps: "as-needed"
bracketSpacing: true
arrowParens: "avoid"

overrides:
  - files: "*.md"
    options:
      proseWrap: "always"
  - files: "*.sol"
    options:
      compiler: "0.8.24"
      parser: "slang"
      tabWidth: 4

